### ISSUE TITLE
Inherit model properties from super classes

### ISSUE THREAD

**Issue by TimothyGillespie** [JavaWebStack/ORM#13]
**Is your feature request related to a problem? Please describe.**
When you look to the last section: I wish that B had the id field as well. Currently, this doesn't seem to be the case. It can lead to reduction of boilerplate code and better maintainability.

I can imagine scenarios where you don't want to inherit these properties. In this case one could add an Annotation on the inheriting class like: @DoNotInheritModelProperties

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
See above.

**Additional context**
´´´
class A extends Model {
    @Column
    int id;
}

class B extends A {}
´´´

**Comment by JanHolger** [comment]
Because of the way inheritance works in java (fields aren't actually inherited to the child class, they only exist on the parent class) this would probably break the current implementation. I thought of this before because you sometimes have quite similar models and might want to inherit fields from a base class. This is something we should consider when rebuilding/decoupling the query builder.
